import type { Asset, AssetCategory } from '@/types/asset';

/**
 * Static local catalog standing in for the future `assets` Supabase table.
 * Adding a real asset later is just appending an entry here (and a matching
 * seed row in supabase/migrations for the documented schema).
 */
export const PLACEHOLDER_ASSETS: Asset[] = [
  {
    id: 'hat-cap',
    category: 'accessories',
    name: 'Baseball Cap',
    thumbnailUrl: '/assets/props/accessories/cap.svg',
    assetUrl: '/assets/props/accessories/cap.svg',
  },
  {
    id: 'hat-top-hat',
    category: 'accessories',
    name: 'Top Hat',
    thumbnailUrl: '/assets/props/accessories/top-hat.svg',
    assetUrl: '/assets/props/accessories/top-hat.svg',
  },
  {
    id: 'hat-beanie',
    category: 'accessories',
    name: 'Beanie',
    thumbnailUrl: '/assets/props/accessories/beanie.svg',
    assetUrl: '/assets/props/accessories/beanie.svg',
  },
  {
    id: 'hat-crown',
    category: 'accessories',
    name: 'Crown',
    thumbnailUrl: '/assets/props/accessories/crown.svg',
    assetUrl: '/assets/props/accessories/crown.svg',
  },
  {
    id: 'hat-wizard',
    category: 'accessories',
    name: 'Wizard Hat',
    thumbnailUrl: '/assets/props/accessories/wizard.svg',
    assetUrl: '/assets/props/accessories/wizard.svg',
  },
  {
    id: 'hat-chef',
    category: 'accessories',
    name: 'Chef Hat',
    thumbnailUrl: '/assets/props/accessories/chef.svg',
    assetUrl: '/assets/props/accessories/chef.svg',
  },
  {
    id: 'hat-party',
    category: 'accessories',
    name: 'Party Hat',
    thumbnailUrl: '/assets/props/accessories/party.svg',
    assetUrl: '/assets/props/accessories/party.svg',
  },
  {
    id: 'hat-viking',
    category: 'accessories',
    name: 'Viking Helmet',
    thumbnailUrl: '/assets/props/accessories/viking.svg',
    assetUrl: '/assets/props/accessories/viking.svg',
  },
  {
    id: 'hat-propeller-beanie',
    category: 'accessories',
    name: 'Propeller Beanie',
    thumbnailUrl: '/assets/props/accessories/propeller-beanie.svg',
    assetUrl: '/assets/props/accessories/propeller-beanie.svg',
  },
  {
    id: 'hat-graduation-cap',
    category: 'accessories',
    name: 'Graduation Cap',
    thumbnailUrl: '/assets/props/accessories/graduation-cap.svg',
    assetUrl: '/assets/props/accessories/graduation-cap.svg',
  },
  {
    id: 'hat-hard-hat',
    category: 'accessories',
    name: 'Hard Hat',
    thumbnailUrl: '/assets/props/accessories/hard-hat.svg',
    assetUrl: '/assets/props/accessories/hard-hat.svg',
  },
  {
    id: 'hat-toque',
    category: 'accessories',
    name: 'Toque',
    thumbnailUrl: '/assets/props/accessories/toque.svg',
    assetUrl: '/assets/props/accessories/toque.svg',
  },
  {
    id: 'glasses-sunglasses',
    category: 'accessories',
    name: 'Sunglasses',
    thumbnailUrl: '/assets/props/accessories/sunglasses.svg',
    assetUrl: '/assets/props/accessories/sunglasses.svg',
  },
  {
    id: 'glasses-round',
    category: 'accessories',
    name: 'Round Glasses',
    thumbnailUrl: '/assets/props/accessories/round-glasses.svg',
    assetUrl: '/assets/props/accessories/round-glasses.svg',
  },
  {
    id: 'accessory-bowtie',
    category: 'accessories',
    name: 'Bowtie',
    thumbnailUrl: '/assets/props/accessories/bowtie.svg',
    assetUrl: '/assets/props/accessories/bowtie.svg',
  },
  {
    id: 'accessory-mustache',
    category: 'accessories',
    name: 'Mustache',
    thumbnailUrl: '/assets/props/accessories/mustache.svg',
    assetUrl: '/assets/props/accessories/mustache.svg',
  },
  {
    id: 'accessory-earrings',
    category: 'accessories',
    name: 'Earrings',
    thumbnailUrl: '/assets/props/accessories/earrings.svg',
    assetUrl: '/assets/props/accessories/earrings.svg',
  },
  {
    id: 'accessory-devil-horns',
    category: 'accessories',
    name: 'Devil Horns',
    thumbnailUrl: '/assets/props/accessories/devil-horns.svg',
    assetUrl: '/assets/props/accessories/devil-horns.svg',
  },
  {
    id: 'accessory-angel-halo',
    category: 'accessories',
    name: 'Angel Halo',
    thumbnailUrl: '/assets/props/accessories/angel-halo.svg',
    assetUrl: '/assets/props/accessories/angel-halo.svg',
  },
  {
    id: 'accessory-cat-ears',
    category: 'accessories',
    name: 'Cat Ears',
    thumbnailUrl: '/assets/props/accessories/cat-ears.svg',
    assetUrl: '/assets/props/accessories/cat-ears.svg',
  },
  {
    id: 'accessory-bunny-ears',
    category: 'accessories',
    name: 'Bunny Ears',
    thumbnailUrl: '/assets/props/accessories/bunny-ears.svg',
    assetUrl: '/assets/props/accessories/bunny-ears.svg',
  },
  {
    id: 'accessory-bear-ears',
    category: 'accessories',
    name: 'Bear Ears',
    thumbnailUrl: '/assets/props/accessories/bear-ears.svg',
    assetUrl: '/assets/props/accessories/bear-ears.svg',
  },
  {
    id: 'accessory-antennae',
    category: 'accessories',
    name: 'Antennae',
    thumbnailUrl: '/assets/props/accessories/antennae.svg',
    assetUrl: '/assets/props/accessories/antennae.svg',
  },
  {
    id: 'accessory-unicorn-horn',
    category: 'accessories',
    name: 'Unicorn Horn',
    thumbnailUrl: '/assets/props/accessories/unicorn-horn.svg',
    assetUrl: '/assets/props/accessories/unicorn-horn.svg',
  },
  {
    id: 'accessory-antlers',
    category: 'accessories',
    name: 'Antlers',
    thumbnailUrl: '/assets/props/accessories/antlers.svg',
    assetUrl: '/assets/props/accessories/antlers.svg',
  },
  {
    id: 'accessory-headphones',
    category: 'accessories',
    name: 'Headphones',
    thumbnailUrl: '/assets/props/accessories/headphones.svg',
    assetUrl: '/assets/props/accessories/headphones.svg',
  },
  {
    id: 'accessory-gaming-headset',
    category: 'accessories',
    name: 'Gaming Headset',
    thumbnailUrl: '/assets/props/accessories/gaming-headset.svg',
    assetUrl: '/assets/props/accessories/gaming-headset.svg',
  },
  {
    id: 'accessory-superhero-cape',
    category: 'accessories',
    name: 'Superhero Cape',
    thumbnailUrl: '/assets/props/accessories/superhero-cape.svg',
    assetUrl: '/assets/props/accessories/superhero-cape.svg',
  },
  {
    id: 'accessory-lanyard',
    category: 'accessories',
    name: 'Lanyard',
    thumbnailUrl: '/assets/props/accessories/lanyard.svg',
    assetUrl: '/assets/props/accessories/lanyard.svg',
  },
  {
    id: 'accessory-bandana',
    category: 'accessories',
    name: 'Bandana',
    thumbnailUrl: '/assets/props/accessories/bandana.svg',
    assetUrl: '/assets/props/accessories/bandana.svg',
  },
  {
    id: 'accessory-coffee-mug',
    category: 'food-drink',
    name: 'Coffee Mug',
    thumbnailUrl: '/assets/props/food-drink/coffee-mug.svg',
    assetUrl: '/assets/props/food-drink/coffee-mug.svg',
  },
  {
    id: 'accessory-bubble-tea',
    category: 'food-drink',
    name: 'Bubble Tea',
    thumbnailUrl: '/assets/props/food-drink/bubble-tea.svg',
    assetUrl: '/assets/props/food-drink/bubble-tea.svg',
  },
  {
    id: 'accessory-wine-glass',
    category: 'food-drink',
    name: 'Wine Glass',
    thumbnailUrl: '/assets/props/food-drink/wine-glass.svg',
    assetUrl: '/assets/props/food-drink/wine-glass.svg',
  },
  {
    id: 'accessory-beer-mug',
    category: 'food-drink',
    name: 'Beer Mug',
    thumbnailUrl: '/assets/props/food-drink/beer-mug.svg',
    assetUrl: '/assets/props/food-drink/beer-mug.svg',
  },
  {
    id: 'accessory-phone',
    category: 'accessories',
    name: 'Phone',
    thumbnailUrl: '/assets/props/accessories/phone.svg',
    assetUrl: '/assets/props/accessories/phone.svg',
  },
  {
    id: 'accessory-game-controller',
    category: 'accessories',
    name: 'Game Controller',
    thumbnailUrl: '/assets/props/accessories/game-controller.svg',
    assetUrl: '/assets/props/accessories/game-controller.svg',
  },
  {
    id: 'accessory-microphone',
    category: 'accessories',
    name: 'Microphone',
    thumbnailUrl: '/assets/props/accessories/microphone.svg',
    assetUrl: '/assets/props/accessories/microphone.svg',
  },
  {
    id: 'accessory-camera',
    category: 'accessories',
    name: 'Camera',
    thumbnailUrl: '/assets/props/accessories/camera.svg',
    assetUrl: '/assets/props/accessories/camera.svg',
  },
  {
    id: 'accessory-book',
    category: 'accessories',
    name: 'Book',
    thumbnailUrl: '/assets/props/accessories/book.svg',
    assetUrl: '/assets/props/accessories/book.svg',
  },
  {
    id: 'accessory-laptop',
    category: 'accessories',
    name: 'Laptop',
    thumbnailUrl: '/assets/props/accessories/laptop.svg',
    assetUrl: '/assets/props/accessories/laptop.svg',
  },
  {
    id: 'accessory-skateboard',
    category: 'accessories',
    name: 'Skateboard',
    thumbnailUrl: '/assets/props/accessories/skateboard.svg',
    assetUrl: '/assets/props/accessories/skateboard.svg',
  },
  {
    id: 'accessory-rubber-duck',
    category: 'accessories',
    name: 'Rubber Duck',
    thumbnailUrl: '/assets/props/accessories/rubber-duck.svg',
    assetUrl: '/assets/props/accessories/rubber-duck.svg',
  },
  {
    id: 'effect-sparkles',
    category: 'effects',
    name: 'Sparkles',
    thumbnailUrl: '/assets/props/effects/sparkles.svg',
    assetUrl: '/assets/props/effects/sparkles.svg',
  },
  {
    id: 'effect-fire',
    category: 'effects',
    name: 'Fire',
    thumbnailUrl: '/assets/props/effects/fire.svg',
    assetUrl: '/assets/props/effects/fire.svg',
  },
  {
    id: 'effect-lightning',
    category: 'effects',
    name: 'Lightning Bolt',
    thumbnailUrl: '/assets/props/effects/lightning.svg',
    assetUrl: '/assets/props/effects/lightning.svg',
  },
  {
    id: 'effect-hearts',
    category: 'effects',
    name: 'Hearts',
    thumbnailUrl: '/assets/props/effects/hearts.svg',
    assetUrl: '/assets/props/effects/hearts.svg',
  },
  {
    id: 'effect-stars',
    category: 'effects',
    name: 'Stars',
    thumbnailUrl: '/assets/props/effects/stars.svg',
    assetUrl: '/assets/props/effects/stars.svg',
  },
  {
    id: 'effect-confetti',
    category: 'effects',
    name: 'Confetti',
    thumbnailUrl: '/assets/props/effects/confetti.svg',
    assetUrl: '/assets/props/effects/confetti.svg',
  },
  {
    id: 'effect-speed-lines',
    category: 'effects',
    name: 'Speed Lines',
    thumbnailUrl: '/assets/props/effects/speed-lines.svg',
    assetUrl: '/assets/props/effects/speed-lines.svg',
  },
  {
    id: 'effect-rainbow',
    category: 'effects',
    name: 'Rainbow',
    thumbnailUrl: '/assets/props/effects/rainbow.svg',
    assetUrl: '/assets/props/effects/rainbow.svg',
  },
  {
    id: 'effect-sweat-drop',
    category: 'effects',
    name: 'Sweat Drop',
    thumbnailUrl: '/assets/props/effects/sweat-drop.svg',
    assetUrl: '/assets/props/effects/sweat-drop.svg',
  },
  {
    id: 'effect-zzz',
    category: 'effects',
    name: 'Zzz',
    thumbnailUrl: '/assets/props/effects/zzz.svg',
    assetUrl: '/assets/props/effects/zzz.svg',
  },
  {
    id: 'background-blush',
    category: 'backgrounds',
    name: 'Blush',
    thumbnailUrl: '/assets/props/backgrounds/blush.svg',
    assetUrl: '/assets/props/backgrounds/blush.svg',
  },
  {
    id: 'background-sky',
    category: 'backgrounds',
    name: 'Sky',
    thumbnailUrl: '/assets/props/backgrounds/sky.svg',
    assetUrl: '/assets/props/backgrounds/sky.svg',
  },
  {
    id: 'background-mint',
    category: 'backgrounds',
    name: 'Mint',
    thumbnailUrl: '/assets/props/backgrounds/mint.svg',
    assetUrl: '/assets/props/backgrounds/mint.svg',
  },
];

export const ASSET_CATEGORIES: AssetCategory[] = ['accessories', 'food-drink', 'effects', 'backgrounds'];

export function getAssetsByCategory(category: AssetCategory): Asset[] {
  return PLACEHOLDER_ASSETS.filter((asset) => asset.category === category);
}

/** Every built-in prop across categories, excluding backgrounds (which aren't placeable props). */
export function getAllProps(): Asset[] {
  return PLACEHOLDER_ASSETS.filter((asset) => asset.category !== 'backgrounds');
}

export function getAssetById(id: string): Asset | undefined {
  return PLACEHOLDER_ASSETS.find((asset) => asset.id === id);
}
